CREATE TABLE payment_methods (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 type VARCHAR(24) NOT NULL CHECK(type IN ('TELEBIRR','BANK_TRANSFER')),
 display_name VARCHAR(100) NOT NULL, account_name VARCHAR(100) NOT NULL,
 destination VARCHAR(150) NOT NULL, instructions VARCHAR(2000) NOT NULL,
 active BOOLEAN NOT NULL, display_order INTEGER NOT NULL CHECK(display_order >= 0),
 revision BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE payment_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES bot_users(id),
 open_user_id BIGINT UNIQUE REFERENCES bot_users(id),
 creation_key VARCHAR(64) NOT NULL,
 status VARCHAR(24) NOT NULL CHECK(status IN ('SELECT_METHOD','AWAITING_REFERENCE','AWAITING_RECEIPT','PENDING_REVIEW','APPROVED','REJECTED','CANCELLED')),
 amount NUMERIC(12,2) NOT NULL CHECK(amount >= 0), currency VARCHAR(3) NOT NULL,
 method_id BIGINT REFERENCES payment_methods(id),
 method_type VARCHAR(24), method_name VARCHAR(100), account_name VARCHAR(100),
 destination VARCHAR(150), instructions VARCHAR(2000),
 reference VARCHAR(100), normalized_reference VARCHAR(100) UNIQUE,
 receipt_file_id VARCHAR(1024), receipt_unique_id VARCHAR(255),
 receipt_type VARCHAR(16), receipt_filename VARCHAR(200), receipt_mime VARCHAR(100), receipt_size BIGINT,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, submitted_at TIMESTAMP WITH TIME ZONE,
 reviewed_at TIMESTAMP WITH TIME ZONE, reviewed_by VARCHAR(64), rejection_reason VARCHAR(500),
 UNIQUE(user_id,creation_key), UNIQUE(id,user_id),
 CHECK((status IN ('SELECT_METHOD','AWAITING_REFERENCE','AWAITING_RECEIPT','PENDING_REVIEW') AND open_user_id IS NOT NULL AND open_user_id=user_id)
    OR (status IN ('APPROVED','REJECTED','CANCELLED') AND open_user_id IS NULL)),
 CHECK(status IN ('SELECT_METHOD','CANCELLED') OR method_id IS NOT NULL),
 CHECK(status NOT IN ('AWAITING_RECEIPT','PENDING_REVIEW','APPROVED','REJECTED') OR normalized_reference IS NOT NULL),
 CHECK(status NOT IN ('PENDING_REVIEW','APPROVED','REJECTED') OR (receipt_file_id IS NOT NULL AND receipt_unique_id IS NOT NULL AND submitted_at IS NOT NULL)),
 CHECK(status NOT IN ('APPROVED','REJECTED') OR (reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)),
 CHECK(receipt_size IS NULL OR receipt_size BETWEEN 1 AND 10485760)
);
CREATE INDEX payment_queue_idx ON payment_requests(status,id);
CREATE INDEX payment_user_history_idx ON payment_requests(user_id,id);
CREATE INDEX payment_method_idx ON payment_requests(method_id,id);
CREATE INDEX payment_receipt_unique_idx ON payment_requests(receipt_unique_id);
