CREATE TABLE lifetime_access_grants (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL UNIQUE REFERENCES bot_users(id),
 payment_request_id BIGINT NOT NULL UNIQUE,
 granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
 granted_by VARCHAR(64) NOT NULL,
 FOREIGN KEY(payment_request_id,user_id) REFERENCES payment_requests(id,user_id)
);
CREATE TABLE payment_audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor_type VARCHAR(16) NOT NULL CHECK(actor_type IN ('USER','WEB_ADMIN','SYSTEM')),
 actor VARCHAR(64) NOT NULL, action VARCHAR(48) NOT NULL,
 entity_type VARCHAR(24) NOT NULL, entity_id BIGINT NOT NULL,
 metadata VARCHAR(500) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX payment_audit_entity_idx ON payment_audit_events(entity_type,entity_id,id);
CREATE INDEX payment_audit_action_idx ON payment_audit_events(action,id);
