CREATE TABLE payment_notifications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 request_id BIGINT NOT NULL REFERENCES payment_requests(id),
 kind VARCHAR(24) NOT NULL CHECK(kind IN ('ADMIN_PENDING','USER_APPROVED','USER_REJECTED')),
 recipient_id BIGINT,
 language VARCHAR(2) NOT NULL,
 status VARCHAR(16) NOT NULL CHECK(status IN ('NEW','SENDING','SENT','FAILED','SKIPPED')),
 attempts INTEGER NOT NULL CHECK(attempts >= 0),
 next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, sent_at TIMESTAMP WITH TIME ZONE,
 UNIQUE(request_id,kind)
);
CREATE INDEX payment_notification_due_idx ON payment_notifications(status,next_attempt_at);
