CREATE TABLE app_settings (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    free_practice_limit INTEGER NOT NULL CHECK (free_practice_limit >= 0),
    free_mock_limit INTEGER NOT NULL CHECK (free_mock_limit >= 0),
    questions_per_mock INTEGER NOT NULL CHECK (questions_per_mock > 0),
    lifetime_price NUMERIC(12,2) NOT NULL CHECK (lifetime_price >= 0),
    currency VARCHAR(3) NOT NULL,
    payment_enabled BOOLEAN NOT NULL,
    manual_payment_enabled BOOLEAN NOT NULL,
    support_info VARCHAR(500) NOT NULL,
    phone_key_fingerprint VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO app_settings VALUES (1, 100, 2, 50, 50.00, 'ETB', FALSE, FALSE, '', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE admin_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(64) NOT NULL,
    action VARCHAR(40) NOT NULL,
    target VARCHAR(80) NOT NULL,
    before_value TEXT NOT NULL,
    after_value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
