CREATE TABLE exam_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    name_am VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_type_id BIGINT NOT NULL REFERENCES exam_types(id),
    code VARCHAR(40) NOT NULL,
    name VARCHAR(100) NOT NULL,
    name_am VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (exam_type_id, code)
);
CREATE INDEX categories_exam_idx ON categories(exam_type_id);
