CREATE TABLE bot_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL UNIQUE CHECK (telegram_user_id > 0),
    preferred_language VARCHAR(2) CHECK (preferred_language IN ('en','am')),
    selected_exam_type_id BIGINT REFERENCES exam_types(id),
    registration_status VARCHAR(24) NOT NULL CHECK (registration_status IN
        ('LANGUAGE_REQUIRED','EXAM_TYPE_REQUIRED','PHONE_REQUIRED','COMPLETED')),
    phone_identity_hash VARCHAR(64) UNIQUE,
    registration_completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (id, phone_identity_hash),
    CHECK (registration_status = 'LANGUAGE_REQUIRED' OR preferred_language IS NOT NULL),
    CHECK (registration_status NOT IN ('PHONE_REQUIRED','COMPLETED') OR selected_exam_type_id IS NOT NULL),
    CHECK ((registration_status = 'COMPLETED' AND phone_identity_hash IS NOT NULL AND registration_completed_at IS NOT NULL)
        OR (registration_status <> 'COMPLETED' AND phone_identity_hash IS NULL AND registration_completed_at IS NULL))
);
CREATE INDEX bot_users_exam_idx ON bot_users(selected_exam_type_id);
CREATE TABLE access_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES bot_users(id),
    phone_identity_hash VARCHAR(64) NOT NULL UNIQUE,
    access_level VARCHAR(16) NOT NULL CHECK (access_level IN ('FREE','LIFETIME')),
    practice_limit INTEGER NOT NULL CHECK (practice_limit >= 0),
    mock_limit INTEGER NOT NULL CHECK (mock_limit >= 0),
    questions_per_mock INTEGER NOT NULL CHECK (questions_per_mock > 0),
    practice_used INTEGER NOT NULL CHECK (practice_used >= 0),
    mocks_used INTEGER NOT NULL CHECK (mocks_used >= 0),
    grant_source VARCHAR(40) NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id, phone_identity_hash) REFERENCES bot_users(id, phone_identity_hash)
);
