CREATE TABLE questions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 current_version_id BIGINT,
 status VARCHAR(16) NOT NULL CHECK(status IN ('DRAFT','REVIEWED','PUBLISHED','ARCHIVED')),
 revision BIGINT NOT NULL DEFAULT 0,
 created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CHECK(status = 'DRAFT' OR current_version_id IS NOT NULL)
);
CREATE TABLE question_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 question_id BIGINT NOT NULL REFERENCES questions(id),
 version_number INTEGER NOT NULL CHECK(version_number > 0),
 exam_type_id BIGINT REFERENCES exam_types(id), category_id BIGINT REFERENCES categories(id),
 exam_name VARCHAR(100) NOT NULL, category_name VARCHAR(100) NOT NULL,
 question_text TEXT NOT NULL, explanation TEXT NOT NULL,
 difficulty VARCHAR(16) NOT NULL CHECK(difficulty IN ('UNSPECIFIED','EASY','MEDIUM','HARD')),
 source_type VARCHAR(100) NOT NULL, source_title VARCHAR(300) NOT NULL,
 source_reference VARCHAR(500) NOT NULL, source_year INTEGER CHECK(source_year BETWEEN 1000 AND 9999),
 source_notes VARCHAR(2000) NOT NULL,
 use_status VARCHAR(32) NOT NULL CHECK(use_status IN ('ORIGINAL','LICENSED','PERMITTED','PUBLIC_DOMAIN','UNKNOWN_REVIEW_REQUIRED','BLOCKED')),
 free_pool BOOLEAN NOT NULL, premium_pool BOOLEAN NOT NULL, mock_pool BOOLEAN NOT NULL,
 fingerprint VARCHAR(64) NOT NULL, stem_fingerprint VARCHAR(64) NOT NULL,
 created_by VARCHAR(64) NOT NULL, reviewed_by VARCHAR(64),
 reviewed_at TIMESTAMP WITH TIME ZONE, published_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE(question_id, version_number), UNIQUE(question_id,id)
);
ALTER TABLE questions ADD CONSTRAINT question_current_version_fk
 FOREIGN KEY(id,current_version_id) REFERENCES question_versions(question_id,id);
CREATE TABLE question_options (
 version_id BIGINT NOT NULL REFERENCES question_versions(id),
 position INTEGER NOT NULL CHECK(position BETWEEN 0 AND 7),
 option_text VARCHAR(2000) NOT NULL, correct BOOLEAN NOT NULL,
 PRIMARY KEY(version_id,position)
);
CREATE INDEX questions_status_idx ON questions(status,id);
CREATE INDEX questions_current_idx ON questions(current_version_id);
CREATE INDEX question_version_exam_idx ON question_versions(exam_type_id,category_id);
CREATE INDEX question_version_category_idx ON question_versions(category_id);
CREATE INDEX question_version_rights_idx ON question_versions(use_status);
CREATE INDEX question_version_fingerprint_idx ON question_versions(exam_type_id,fingerprint);
CREATE INDEX question_version_stem_idx ON question_versions(exam_type_id,stem_fingerprint);
