CREATE TABLE question_import_batches (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 filename VARCHAR(200) NOT NULL, file_type VARCHAR(8) NOT NULL CHECK(file_type IN ('CSV','XLSX')),
 actor VARCHAR(64) NOT NULL, status VARCHAR(24) NOT NULL
 CHECK(status IN ('VALIDATED','REVIEW_REQUIRED','IMPORTED','CANCELLED','FAILED')),
 total_rows INTEGER NOT NULL CHECK(total_rows BETWEEN 0 AND 500),
 valid_rows INTEGER NOT NULL CHECK(valid_rows >= 0), invalid_rows INTEGER NOT NULL CHECK(invalid_rows >= 0),
 duplicate_rows INTEGER NOT NULL CHECK(duplicate_rows >= 0), imported_rows INTEGER NOT NULL CHECK(imported_rows >= 0),
 failed_rows INTEGER NOT NULL CHECK(failed_rows >= 0),
 completed_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE question_import_rows (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id BIGINT NOT NULL REFERENCES question_import_batches(id),
 row_number INTEGER NOT NULL CHECK(row_number >= 2),
 payload TEXT NOT NULL, question_preview VARCHAR(300) NOT NULL,
 exam_code VARCHAR(40) NOT NULL, category_code VARCHAR(40) NOT NULL, use_status VARCHAR(32) NOT NULL,
 errors VARCHAR(2000) NOT NULL, duplicate_status VARCHAR(24) NOT NULL
 CHECK(duplicate_status IN ('UNIQUE','EXACT_DUPLICATE','LIKELY_DUPLICATE')),
 duplicate_reason VARCHAR(300) NOT NULL,
 question_id BIGINT UNIQUE REFERENCES questions(id),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE(batch_id,row_number)
);
CREATE INDEX question_import_status_idx ON question_import_batches(status,id);
CREATE INDEX question_import_rows_batch_idx ON question_import_rows(batch_id,row_number);
