CREATE TABLE practice_deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES bot_users(id),
 question_id BIGINT NOT NULL, version_id BIGINT NOT NULL,
 category_filter BIGINT REFERENCES categories(id),
 next_delivery_id BIGINT REFERENCES practice_deliveries(id),
 review_delivery_id BIGINT REFERENCES practice_deliveries(id),
 selected_option INTEGER,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 answered_at TIMESTAMP WITH TIME ZONE,
 FOREIGN KEY(question_id,version_id) REFERENCES question_versions(question_id,id),
 FOREIGN KEY(version_id,selected_option) REFERENCES question_options(version_id,position),
 UNIQUE(id,user_id,question_id),
 CHECK((selected_option IS NULL AND answered_at IS NULL) OR (selected_option IS NOT NULL AND answered_at IS NOT NULL))
);
CREATE INDEX practice_deliveries_user_idx ON practice_deliveries(user_id,id);
CREATE INDEX practice_deliveries_question_idx ON practice_deliveries(user_id,question_id,id);
CREATE TABLE practice_usage (
 user_id BIGINT NOT NULL REFERENCES bot_users(id),
 question_id BIGINT NOT NULL REFERENCES questions(id),
 first_delivery_id BIGINT NOT NULL UNIQUE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 PRIMARY KEY(user_id,question_id),
 FOREIGN KEY(first_delivery_id,user_id,question_id) REFERENCES practice_deliveries(id,user_id,question_id)
);
CREATE TABLE practice_sessions (
 user_id BIGINT PRIMARY KEY REFERENCES bot_users(id),
 current_delivery_id BIGINT NOT NULL REFERENCES practice_deliveries(id)
);
