CREATE TABLE mock_attempts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES bot_users(id),
 active_user_id BIGINT UNIQUE REFERENCES bot_users(id),
 exam_type_id BIGINT NOT NULL REFERENCES exam_types(id),
 creation_key VARCHAR(64) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('READY','IN_PROGRESS','SUBMITTED','EXPIRED')),
 question_count INTEGER NOT NULL CHECK(question_count > 0),
 duration_minutes INTEGER CHECK(duration_minutes BETWEEN 1 AND 1440),
 cursor_position INTEGER NOT NULL DEFAULT 0 CHECK(cursor_position >= 0),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 started_at TIMESTAMP WITH TIME ZONE,
 deadline_at TIMESTAMP WITH TIME ZONE,
 first_answer_at TIMESTAMP WITH TIME ZONE,
 submitted_at TIMESTAMP WITH TIME ZONE,
 correct_count INTEGER, incorrect_count INTEGER, unanswered_count INTEGER,
 UNIQUE(user_id,creation_key),
 CHECK((status IN ('READY','IN_PROGRESS') AND active_user_id IS NOT NULL AND active_user_id=user_id)
    OR (status IN ('SUBMITTED','EXPIRED') AND active_user_id IS NULL)),
 CHECK((status IN ('READY','IN_PROGRESS') AND submitted_at IS NULL)
    OR (status IN ('SUBMITTED','EXPIRED') AND submitted_at IS NOT NULL)),
 CHECK(correct_count IS NULL OR correct_count >= 0),
 CHECK(incorrect_count IS NULL OR incorrect_count >= 0),
 CHECK(unanswered_count IS NULL OR unanswered_count >= 0)
);
CREATE INDEX mock_attempt_user_history_idx ON mock_attempts(user_id,id);
CREATE TABLE mock_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 attempt_id BIGINT NOT NULL REFERENCES mock_attempts(id),
 sequence_number INTEGER NOT NULL CHECK(sequence_number >= 0),
 question_id BIGINT NOT NULL, version_id BIGINT NOT NULL,
 selected_option INTEGER, answer_revision INTEGER NOT NULL DEFAULT 0,
 answered_at TIMESTAMP WITH TIME ZONE,
 UNIQUE(attempt_id,sequence_number), UNIQUE(attempt_id,question_id),
 FOREIGN KEY(question_id,version_id) REFERENCES question_versions(question_id,id),
 FOREIGN KEY(version_id,selected_option) REFERENCES question_options(version_id,position),
 CHECK((selected_option IS NULL AND answered_at IS NULL) OR (selected_option IS NOT NULL AND answered_at IS NOT NULL))
);
